# 1. NUMPYの基礎知識

In [1]:
# NumPyは多次元配列に使われる線形代数ライブラリである。
# NumPyは、(1)C/Fortranの計算効率と、(2)Python言語の簡単な構文、という2つの世界の長所を持ち合わせています。

import numpy as np 

# 1次元の配列を定義してみましょう 
my_list = [10, 20, 50, 60, 70]
my_list

[10, 20, 50, 60, 70]

In [2]:
# リスト "my_list "からnumpy配列を作ってみよう
x = np.array(my_list)
x

array([10, 20, 50, 60, 70])

In [3]:
type(x)

numpy.ndarray

In [4]:
# 多次元（行列の定義） 
matrix = np.array([[5, 8], [9, 13]])
matrix

array([[ 5,  8],
       [ 9, 13]])

**ミニチャレンジ1：***。
- **以下の2x4 numpy配列を作成するコードを書いてください**。

```
[[4 6 8 7] 
[20 5 6 9]]
```

# 2. 組み込みのメソッドと関数 

In [5]:
# "rand()" 0と1の間の一様分布
x = np.random.rand(15)
x

array([0.82236129, 0.22685685, 0.15037582, 0.4421327 , 0.22466544,
       0.41993657, 0.03762509, 0.5424838 , 0.43127593, 0.33673612,
       0.17938372, 0.34671662, 0.79903111, 0.41982575, 0.53221023])

In [6]:
# 同様に乱数の行列を作ることもできる
x = np.random.rand(5, 5)
x

array([[0.13001619, 0.36935024, 0.02610569, 0.53982294, 0.09768741],
       [0.02764129, 0.32703395, 0.34593933, 0.84798382, 0.59833571],
       [0.62629639, 0.45033981, 0.88309074, 0.97017907, 0.75109747],
       [0.57281706, 0.29529952, 0.2451627 , 0.78976167, 0.3745051 ],
       [0.8134389 , 0.43990659, 0.56707422, 0.57251111, 0.88268909]])

In [7]:
# "randint "は、次のように、ある数のランダムな整数を生成するために使用できます。
x = np.random.randn(10)
x

array([-0.84967156, -0.48939761, -0.46714175,  0.1019317 , -0.05704375,
        0.14690481,  1.27677807, -1.6308906 ,  0.84149364,  1.18344312])

In [8]:
# np.arange は、与えられた区間内で等間隔の値を生成します。
x = np.random.randint(1, 10)
x

2

In [9]:
# 5のステップで等間隔の値を作る
x = np.random.randint(1, 100, 15)
x

array([67, 67, 98, 64,  9, 99, 69, 97, 23, 85, 82, 83, 21, 56, 12])

In [10]:
# 1の対角線を作り、それ以外の場所には0を置く
x = np.arange(1, 50)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [11]:
# 1の配列
x = np.arange(1, 50, 5)
x

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [12]:
#1の対角線を作り、それ以外の場所には0を置く
x = np.eye(15)
x

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [13]:
# 1の配列
x = np.ones(10)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
# 演算子のマトリクス
x = np.ones((15, 15))
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.

In [15]:
# 零点の配列
x = np.zeros(50)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**ミニチャレンジ #2:**
- **ユーザーから数字xを受け取り、0からxまでの乱数で1x20の配列を作成するコードを書いてください**。


# 3. 形、長さ、タイプ、再形成、最大/最小値

In [16]:
# 1次元の配列を定義してみよう 
my_list = [-30, 4, 50, 60, 29, 15, 22, 90]
my_list
x = np.array(my_list)
x

array([-30,   4,  50,  60,  29,  15,  22,  90])

In [17]:
# numpyの配列の長さを得る
len(x)

8

In [18]:
# 形状の取得
x.shape

(8,)

In [19]:
# データ型の取得
matrix.dtype

dtype('int64')

In [20]:
# 1次元配列を行列にリシェイプする
z = x.reshape(2,4)
print(x)
print(z)

[-30   4  50  60  29  15  22  90]
[[-30   4  50  60]
 [ 29  15  22  90]]


In [21]:
# 最大要素（値）の取得
x.max()

90

In [22]:
# 最小要素(値)の取得
x.min()

-30

In [23]:
# 最大要素の位置を求める
x.argmax()

7

In [24]:
# 最小要素の位置を取得する
x.argmin()

0

**ミニ・チャレンジ #3
- 要素間の差が10になるような、300から500までの数字を含む4x5の配列を作成するコードを書いてください。


**ミニ・チャレンジ #4:**
- 20x20のnumpy配列を作成し、最大値、最小値、平均値を求めるコードを作成してください**。


# 4. 数学演算

In [25]:
# np.arange()は、与えられた区間内の等間隔の値を返す。
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
y = np.arange(1, 10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
# 2つのnumpy配列を足し合わせる
sum = x+y
sum

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [28]:
squared = x**2
squared

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [29]:
sqrt = np.sqrt(squared)
sqrt

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [30]:
z = np.exp(y)
z

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

**ミニチャレンジ #5:**
- 以下のXとYの値が与えられたとき、それらの間の距離を求めなさい**。


```
X = [3, 20, 30]
Y = [4, 6, 7]
```

# 5. スライスとインデックスの作成 

In [31]:
x = np.array([20, 40, 50, 21, 15])
x

array([20, 40, 50, 21, 15])

In [32]:
# numpy配列から特定のインデックスにアクセスする
x[0]

20

In [33]:
# 最初のインデックス0から始まり，最後の要素を含まないまで
x[0:3]

array([20, 40, 50])

In [34]:
# numpy配列の複数の値を一度に変更するブロードキャスト
x[0:2] = 10
x

array([10, 10, 50, 21, 15])

In [35]:
# 2次元のnumpy配列を定義しよう
matrix = np.random.randint(1,10, (5, 5))
matrix

array([[1, 9, 8, 9, 6],
       [1, 6, 6, 8, 6],
       [4, 7, 8, 7, 5],
       [8, 1, 3, 5, 7],
       [7, 3, 5, 8, 6]])

In [36]:
# mtrixから行を取得する
matrix[2]

array([4, 7, 8, 7, 5])

In [37]:
# 1つの要素を得る
matrix[0][2]

8

In [38]:
mini_matrix = matrix[:3]
mini_matrix

array([[1, 9, 8, 9, 6],
       [1, 6, 6, 8, 6],
       [4, 7, 8, 7, 5]])

In [39]:
mini_matrix = matrix[2:]
mini_matrix

array([[4, 7, 8, 7, 5],
       [8, 1, 3, 5, 7],
       [7, 3, 5, 8, 6]])

In [40]:
mini_matrix = matrix[:, :2]
mini_matrix

array([[1, 9],
       [1, 6],
       [4, 7],
       [8, 1],
       [7, 3]])

In [41]:
mini_matrix = matrix[:, 2:]
mini_matrix

array([[8, 9, 6],
       [6, 8, 6],
       [8, 7, 5],
       [3, 5, 7],
       [5, 8, 6]])

**ミニチャレンジ #6:**
- **次の行列では、最後の行を-1で置き換えてください**。
- **右上の2x2の行列を2倍してください**。



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



# 6. 要素の選択 (条件付き)

In [42]:
matrix = np.random.randint(1,10, (5, 5))
matrix

array([[1, 7, 9, 4, 3],
       [4, 4, 9, 7, 1],
       [2, 5, 7, 2, 6],
       [1, 4, 2, 3, 2],
       [9, 5, 8, 6, 6]])

In [43]:
new_matrix = matrix[matrix>3]
new_matrix

array([7, 9, 4, 4, 4, 9, 7, 5, 7, 6, 4, 9, 5, 8, 6, 6])

In [44]:
new_matrix = matrix[matrix%2==0]
new_matrix

array([4, 4, 4, 2, 2, 6, 4, 2, 2, 8, 6, 6])

**ミニチャレンジ #7:**
- **次の行列では、負の要素を0に、奇数の要素を25に置き換えてください**。



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


# EXCELLENT JOB!

# MINI CHALLENGES SOLUTIONS

**ミニチャレンジ #1 解決策:** 
- **以下の2x4 numpy配列を作成するコードを書いてください**。

```
[[4 6 8 7] 
[20 5 6 9]]
```

In [45]:
x = np.array([[[4, 6, 8, 7] , [20, 5, 6, 9]]])
x

array([[[ 4,  6,  8,  7],
        [20,  5,  6,  9]]])

**ミニチャレンジ2の解答：***。
- ユーザーから数値xを受け取り、0からxまでの乱数で1x20の配列を作成するコードを書いてください。


In [56]:
x = int(input("Please enter a positive integer value: "))
x = np.random.randint(1, x, 20)
x

Please enter a positive integer value: 20


array([14, 15,  5,  8, 11,  6, 12, 17, 12, 18, 18,  8, 14, 14, 16,  2, 19,
       12, 10, 13])

**ミニチャレンジ#3の解答:**
- 要素間の差が10になるような、300から500までの数字を含む4x5の配列を作成するコードを書いてください。


In [47]:
x = np.arange(300, 500, 10)
x.shape

(20,)

In [48]:
x = x.reshape(4, 5)
print(x)

[[300 310 320 330 340]
 [350 360 370 380 390]
 [400 410 420 430 440]
 [450 460 470 480 490]]


**ミニチャレンジ #4 解決策： **


In [49]:
x = np.random.randint(-1000, 1000, (20, 20))
print(x)
print('The maximum value is: {} and the minimum value is:{}'.format(x.min(), x.max()))

[[ -619  -191   359   761  -227  -766   -28   775    29   107   372  -413
    427   216   794  -795   771   910  -911    30]
 [ -440    19   231  -999   954   955  -329   187   -44   806   158   329
    184   470   570   326  -602   908   533  -704]
 [ -849  -460  -832   786   920   -62   915   109  -872   525   309   -86
   -103  -521  -625  -166   525   115  -384    44]
 [ -355   645  -924  -746   823  -636  -449   618   127  -736    99  -481
   -804  -383   424   818   -11   663    16  -471]
 [  879  -946  -957  -829  -873  -531  -263  -379  -838   663   832   887
   -841  -660   474   917   995   170  -843  -610]
 [ -595  -930  -737   680   319  -941  -830   -95  -631   479  -915  -758
    762   815  -802  -643   -20  -363  -474    97]
 [  877  -322  -198  -513   674   -95  -680   687  -467  -797    -9  -149
     44   842  -494  -580  -420   740   761   110]
 [  387  -961   812   -99    78   118  -985  -829  -643   612   136   417
   -200  -824  -752   327  -293   357   218   423]


**ミニチャレンジ#5の解答：***。
- 以下のXとYの値が与えられたとき、それらの間の距離を求めなさい**。


```
X = [3, 20, 30]
Y = [4, 6, 7]
```




In [50]:
X = np.array([3, 20, 30])
Y = np.array([4, 6, 7])
Z = np.sqrt(X**2 + Y**2)
Z

array([ 5.        , 20.88061302, 30.8058436 ])

**ミニチャレンジ #6 解答:**
- **次の行列では、最後の行を-1に置き換えます**。
- **右上の2x2行列を2倍します**。



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```




In [51]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])


In [52]:
X[4] = 0
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

In [53]:
X[:2, 3:]  = X[:2, 3:] * 2

In [54]:
X

array([[ 2, 30, 20, -4, -8],
       [ 3,  4, 40, -6, -4],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

**ミニチャレンジ#7の解答：***。
- 以下の行列において，負の要素を0に，奇数の要素を25に置き換えてください**。


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [55]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

X[X%2==1] = 25
X[X<0] = 0
X

array([[ 2, 30, 20,  0,  0],
       [25,  4, 40, 25,  0],
       [25,  4,  0, 90, 10],
       [25, 25, 34, 22, 12],
       [25, 24, 22, 32, 25]])